/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package id.sch.smkn1kawali.penjualanmotor.views.mains;

import id.sch.smkn1kawali.penjualanmotor.controllers.ControllerMotor;
import id.sch.smkn1kawali.penjualanmotor.interfaces.InterfaceMotor;
import id.sch.smkn1kawali.penjualanmotor.models.Motor;
import id.sch.smkn1kawali.penjualanmotor.models.User;
import id.sch.smkn1kawali.penjualanmotor.models.tables.TableMotor;
import id.sch.smkn1kawali.penjualanmotor.utilitys.DateRenderer;
import id.sch.smkn1kawali.penjualanmotor.utilitys.Messages;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Acer One
 */
public class FrmMasterMotor extends javax.swing.JFrame {
    InterfaceMotor i;
    
    public String aksi, kode, jenis, tipe, warna, gambar, status, ket;
    public Integer harga, stok;
    String name;
    BufferedImage image;
    
    /**
     * Creates new form FrmMasterKaryawan
     */
    public FrmMasterMotor() {
        initComponents();
        i = new ControllerMotor();
        tKode.setEnabled(false);
    }
    
    //coding untuk membuat nomor kode user otomatis bertambah 1,
    //jika tombol TAMBAH di tekan
    private void buatnomor() {
        try {
            Motor m = new Motor();
            i.createId(m);
            tKode.setText(m.getKode());
        } catch (SQLException ex) {
            Messages.setErrorMessage("Ada kesalahan dalam SQL statement..!");
        }
    }
    
    private void bersih() {
        buatnomor();
        cbJenis.setSelectedIndex(0);
        cbTipe.setSelectedIndex(0);
        cbWarna.setSelectedIndex(0);
        tHarga.setText("");
        tGambar.setText("");
        lGambar.setIcon(null);
        tStok.setText("");
        buttonGroup2.clearSelection();
        tKet.setText("");
    }
    
    private void setEditOff() {
        cbJenis.setEnabled(false);
        cbTipe.setEnabled(false);
        cbWarna.setEnabled(false);
        tHarga.setEnabled(false);
        rbAktif.setEnabled(false);
        rbTidakAktif.setEnabled(false);
        tKet.setEnabled(false);
    }
    
    private void edit() {
        tKode.setText(kode);
        cbJenis.setSelectedItem(jenis);
        cbTipe.setSelectedItem(tipe);
        cbWarna.setSelectedItem(warna);
        tHarga.setText(harga.toString());
        tGambar.setText(gambar);
        lGambar.setIcon(resizeImage("src/id/sch/smkn1kawali/penjualanmotor/resources/" + gambar));
        tStok.setText(stok.toString());
        if (status.equals("AKTIF")) {
            rbAktif.setSelected(true);
        } else {
            rbTidakAktif.setSelected(true);
        }
        tKet.setText(ket);
    }
    
    private void validasi() {
        switch (aksi) {
            case "INSERT":
                bersih();
                jLabel1.setText("Tambah Data");
                break;
            case "UPDATE":
                edit();
                jLabel1.setText("Edit Data");
                break;
            default:
                edit();
                setEditOff();
                jLabel1.setText("View Data");
                btnSimpan.setVisible(false);
                break;
        }
    }
    
    private ImageIcon resizeImage(String ImagePath) {
        ImageIcon icon = new ImageIcon(ImagePath);
        Image image = icon.getImage();
        Image img = image.getScaledInstance(lGambar.getWidth(), lGambar.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon imageIcon = new ImageIcon(img);
        return imageIcon;
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tKode = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        rbAktif = new javax.swing.JRadioButton();
        rbTidakAktif = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tKet = new javax.swing.JTextArea();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        tGambar = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        btnSimpan = new javax.swing.JButton();
        tStok = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        lGambar = new javax.swing.JLabel();
        cbWarna = new javax.swing.JComboBox<>();
        cbTipe = new javax.swing.JComboBox<>();
        cbJenis = new javax.swing.JComboBox<>();
        tHarga = new javax.swing.JTextField();
        btnBrowse = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(42, 39, 41));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("View Data");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Kode Motor");

        tKode.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Jenis");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Type");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Status");

        rbAktif.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup2.add(rbAktif);
        rbAktif.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        rbAktif.setText("AKTIF");

        rbTidakAktif.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup2.add(rbTidakAktif);
        rbTidakAktif.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        rbTidakAktif.setText("TIDAK AKTIF");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("Harga");

        tKet.setColumns(20);
        tKet.setRows(5);
        jScrollPane1.setViewportView(tKet);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("Gambar");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setText("Stok");

        tGambar.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        tGambar.setEnabled(false);

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setText("Warna");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel10.setText("Keterangan");

        btnSimpan.setBackground(new java.awt.Color(42, 39, 41));
        btnSimpan.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnSimpan.setForeground(new java.awt.Color(255, 255, 255));
        btnSimpan.setText("Simpan");
        btnSimpan.setBorder(null);
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });

        tStok.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        tStok.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tStokKeyTyped(evt);
            }
        });

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lGambar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lGambar, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );

        cbWarna.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        cbWarna.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-Pilih", "Hitam", "Kuning", "Merah", "Abu-Abu", "Biru", "Pink", "Putih" }));

        cbTipe.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        cbTipe.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-Pilih-", "Beat", "Vario", "Scoopy", "Revo", "Supra X 125", "Verza", "CB150R", "CBR 150 CC", "CBR 250 CC" }));

        cbJenis.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        cbJenis.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-Pilih-", "Matic", "Bebek", "Sport" }));

        tHarga.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        tHarga.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tHargaKeyTyped(evt);
            }
        });

        btnBrowse.setBackground(new java.awt.Color(42, 39, 41));
        btnBrowse.setIcon(new javax.swing.ImageIcon(getClass().getResource("/id/sch/smkn1kawali/penjualanmotor/images/image-2-16.png"))); // NOI18N
        btnBrowse.setBorder(null);
        btnBrowse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBrowseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(107, 107, 107)
                        .addComponent(rbAktif)
                        .addGap(2, 2, 2)
                        .addComponent(rbTidakAktif))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(75, 75, 75)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(238, 238, 238)
                        .addComponent(btnSimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel7))
                        .addGap(96, 96, 96)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tStok, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(tGambar, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnBrowse, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(1, 1, 1))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(71, 71, 71)
                        .addComponent(tKode, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel6)
                            .addGap(108, 108, 108)
                            .addComponent(tHarga))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel4)
                                .addComponent(jLabel9)
                                .addComponent(jLabel3))
                            .addGap(105, 105, 105)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(cbWarna, 0, 207, Short.MAX_VALUE)
                                .addComponent(cbTipe, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cbJenis, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addGap(0, 27, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(tKode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cbJenis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cbTipe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(cbWarna, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(tHarga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel7)
                        .addComponent(tGambar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnBrowse, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tStok, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jLabel5))
                    .addComponent(rbAktif)
                    .addComponent(rbTidakAktif))
                .addGap(7, 7, 7)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnSimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
       validasi();
    }//GEN-LAST:event_formWindowOpened

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        // TODO add your handling code here:
        if (cbJenis.getSelectedIndex() == 0 || cbTipe.getSelectedIndex() == 0
                || cbWarna.getSelectedIndex() == 0 || tHarga.getText().isEmpty()
                || tGambar.getText().isEmpty() || lGambar.getIcon() == null
                || tStok.getText().isEmpty() || rbAktif.isSelected() == false
                && rbTidakAktif.isSelected() == false || tKet.getText().isEmpty()) {
            Messages.setErrorMessage("Lengkapi data terlebih dahulu..!");
        } else if (tHarga.getText().length() < 7 || tHarga.getText().length() > 8) {
            Messages.setErrorMessage("Harga berisi 7-8 digit angka");
        } else {
            String status;
            if (rbAktif.isSelected()) {
                status = "AKTIF";
            } else {
                status = "TIDAK AKTIF";
            }
            try {
                int hrg = Integer.parseInt(tHarga.getText());
                int stok = Integer.parseInt(tStok.getText());
                Motor m = new Motor();
                m.setKode(tKode.getText());
                m.setJenis(cbJenis.getSelectedItem().toString());
                m.setType(cbTipe.getSelectedItem().toString());
                m.setWarna(cbWarna.getSelectedItem().toString());
                m.setHarga(hrg);
                m.setStok(stok);
                m.setStatus(status);
                m.setKeterangan(tKet.getText());
                if ("INSERT".equals(aksi)) {
                    //Menambah record baru ke database
                    m.setGambar(name + ".png");
                    ImageIO.write(image, "png", new File("src/id/sch/smkn1kawali/penjualanmotor/resources/" + name + ".png"));
                    i.insert(m);
                    Messages.setInfomationMessage("Data telah berhasil disimpan");
                    bersih();
                } else {
                    //Mengubah record yang sudah ada di database
                    if (tGambar.getText().equals(gambar)) {
                        m.setGambar(tGambar.getText());
                        i.update(m);
                        dispose();
                    } else {
                        File file = new File("src/id/sch/smkn1kawali/penjualanmotor/resources/" + gambar);
                        file.delete();
                        m.setGambar(name + ".png");
                        ImageIO.write(image, "png", new File("src/id/sch/smkn1kawali/penjualanmotor/resources/" + name + ".png")); 
                        i.update(m);
                        dispose();
                    }
                    Messages.setInfomationMessage("Data telah berhasil diperbaharui");
                }
            } catch (SQLException ex) {
                Messages.setErrorMessage("Ada kesalahan dalam SQL statement..!" + ex.toString());
            } catch (IOException ex) {
                Logger.getLogger(ControllerMotor.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void tHargaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tHargaKeyTyped
        // TODO add your handling code here:
        if (!Character.isDigit(evt.getKeyChar())) {
            evt.consume();
        }
    }//GEN-LAST:event_tHargaKeyTyped

    private void tStokKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tStokKeyTyped
        // TODO add your handling code here:
        if (!Character.isDigit(evt.getKeyChar())) {
            evt.consume();
        }
    }//GEN-LAST:event_tStokKeyTyped

    private void btnBrowseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBrowseActionPerformed
        // TODO add your handling code here:
        JFileChooser chooser = new JFileChooser();
        FileNameExtensionFilter filter = new FileNameExtensionFilter("Image Files(*.jpg; *.jpeg; *.png; *.gif; *.bmp)", "jpg", "jpeg", "png", "gif", "bmp");
        chooser.setFileFilter(filter);
        int result = chooser.showOpenDialog(this);
        if (result == JFileChooser.APPROVE_OPTION) {
            File file = chooser.getSelectedFile();
            Date tgl = new Date();
            SimpleDateFormat sdf = new SimpleDateFormat("yyyyMMddHHmmss");
            name = sdf.format(tgl);
            tGambar.setText(file.getName());
            try {
                image = ImageIO.read(file);
                
            } catch (IOException ex) {
                Logger.getLogger(FrmMasterMotor.class.getName()).log(Level.SEVERE, null, ex);
            }
            String path = file.getAbsolutePath();
            lGambar.setIcon(resizeImage(path));
        }
    }//GEN-LAST:event_btnBrowseActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
        switch(aksi) {
            case "VIEW":
                new FrmRiwayatMotor().show();
                this.dispose();
                break;
            default:
                this.dispose();
                break;
        }
    }//GEN-LAST:event_formWindowClosed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmMasterMotor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmMasterMotor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmMasterMotor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmMasterMotor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmMasterMotor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBrowse;
    private javax.swing.JButton btnSimpan;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JComboBox<String> cbJenis;
    private javax.swing.JComboBox<String> cbTipe;
    private javax.swing.JComboBox<String> cbWarna;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lGambar;
    private javax.swing.JRadioButton rbAktif;
    private javax.swing.JRadioButton rbTidakAktif;
    private javax.swing.JTextField tGambar;
    private javax.swing.JTextField tHarga;
    private javax.swing.JTextArea tKet;
    private javax.swing.JTextField tKode;
    private javax.swing.JTextField tStok;
    // End of variables declaration//GEN-END:variables
}
