/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package id.sch.smkn1kawali.penjualanmotor.views.mains;

import id.sch.smkn1kawali.penjualanmotor.controllers.ControllerPelanggan;
import id.sch.smkn1kawali.penjualanmotor.interfaces.InterfacePelanggan;
import id.sch.smkn1kawali.penjualanmotor.models.Pelanggan;
import id.sch.smkn1kawali.penjualanmotor.utilitys.Messages;
import id.sch.smkn1kawali.penjualanmotor.views.FrmMenuUtama;
import java.awt.event.KeyEvent;
import java.sql.SQLException;

/**
 *
 * @author Acer One
 */
public class FrmMasterPelanggan extends javax.swing.JFrame {
    InterfacePelanggan i;
    public String aksi, kode, nik, nama, jk, alamat, kk, telp, status, ket;
    
    /**
     * Creates new form FrmMasterPelanggan
     */
    public FrmMasterPelanggan() {
        initComponents();
        i = new ControllerPelanggan();
        tKode.setEnabled(false);
    }
    
    //coding untuk membuat nomor kode pelanggan otomatis bertambah 1,
    //jika tombol TAMBAH di tekan
    private void buatnomor() {
        try {
            Pelanggan k = new Pelanggan();
            i.createId(k);
            tKode.setText(k.getKode());
        } catch (SQLException ex) {
            Messages.setErrorMessage("Ada kesalahan dalam SQL statement..!");
        }
    }
    
    private void bersih() {
        buatnomor();
        tNik.setText("");
        tNama.setText("");
        buttonGroup1.clearSelection();
        tAlamat.setText("");
        tKK.setText("");
        tTelepon.setText("");
        buttonGroup2.clearSelection();
        tKet.setText("");
    }
    
    private void setEditOff() {
        tNik.setEnabled(false);
        tNama.setEnabled(false);
        rbLaki.setEnabled(false);
        rbPerempuan.setEnabled(false);
        tAlamat.setEnabled(false);
        tKK.setEnabled(false);
        tTelepon.setEnabled(false);
        rbAktif.setEnabled(false);
        rbTidakAktif.setEnabled(false);
        tKet.setEnabled(false);
    }
    
    private void edit() {
        tKode.setText(kode);
        tNik.setText(nik);
        tNama.setText(nama);
        if (jk.equals("Laki-Laki")) {
            rbLaki.setSelected(true);
        } else {
            rbPerempuan.setSelected(true);
        }
        tAlamat.setText(alamat);
        tKK.setText(kk);
        tTelepon.setText(telp);
        if (status.equals("AKTIF")) {
            rbAktif.setSelected(true);
        } else {
            rbTidakAktif.setSelected(true);
        }
        tKet.setText(ket);
    }
    
    private void validasi() {
        switch (aksi) {
            case "INSERT":
                bersih();
                jLabel1.setText("Tambah Data");
                break;
            case "UPDATE":
                edit();
                jLabel1.setText("Edit Data");
                break;
            default:
                edit();
                setEditOff();
                jLabel1.setText("View Data");
                btnSimpan.setVisible(false);
                break;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tKode = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tNik = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tNama = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        rbAktif = new javax.swing.JRadioButton();
        rbTidakAktif = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tKet = new javax.swing.JTextArea();
        jLabel7 = new javax.swing.JLabel();
        tKK = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        tTelepon = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        rbLaki = new javax.swing.JRadioButton();
        rbPerempuan = new javax.swing.JRadioButton();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tAlamat = new javax.swing.JTextArea();
        btnSimpan = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(42, 39, 41));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Tambah Data");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 383, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Kode Pelanggan");

        tKode.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("NIK");

        tNik.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        tNik.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tNikKeyTyped(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Nama Pelanggan");

        tNama.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        tNama.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tNamaKeyTyped(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Status");

        rbAktif.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup2.add(rbAktif);
        rbAktif.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        rbAktif.setText("AKTIF");

        rbTidakAktif.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup2.add(rbTidakAktif);
        rbTidakAktif.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        rbTidakAktif.setText("TIDAK AKTIF");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("Alamat");

        tKet.setColumns(20);
        tKet.setRows(5);
        jScrollPane1.setViewportView(tKet);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("No. KK");

        tKK.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        tKK.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tKKKeyTyped(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setText("No. Telp");

        tTelepon.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        tTelepon.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tTeleponKeyTyped(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setText("Jenis Kelamin");

        rbLaki.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(rbLaki);
        rbLaki.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        rbLaki.setText("Laki-Laki");

        rbPerempuan.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(rbPerempuan);
        rbPerempuan.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        rbPerempuan.setText("Perempuan");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel10.setText("Keterangan");

        tAlamat.setColumns(20);
        tAlamat.setRows(5);
        jScrollPane2.setViewportView(tAlamat);

        btnSimpan.setBackground(new java.awt.Color(42, 39, 41));
        btnSimpan.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnSimpan.setForeground(new java.awt.Color(255, 255, 255));
        btnSimpan.setText("Simpan");
        btnSimpan.setBorder(null);
        btnSimpan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel2)
                .addGap(46, 46, 46)
                .addComponent(tKode, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel3)
                .addGap(123, 123, 123)
                .addComponent(tNik, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel4)
                .addGap(41, 41, 41)
                .addComponent(tNama, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel9)
                .addGap(64, 64, 64)
                .addComponent(rbLaki)
                .addGap(0, 0, 0)
                .addComponent(rbPerempuan))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel6)
                .addGap(102, 102, 102)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel7)
                .addGap(104, 104, 104)
                .addComponent(tKK, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel8)
                .addGap(95, 95, 95)
                .addComponent(tTelepon, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel5)
                .addGap(107, 107, 107)
                .addComponent(rbAktif)
                .addGap(2, 2, 2)
                .addComponent(rbTidakAktif))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel10)
                .addGap(75, 75, 75)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(262, 262, 262)
                .addComponent(btnSimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(tKode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(tNik, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(tNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jLabel9))
                    .addComponent(rbLaki)
                    .addComponent(rbPerempuan))
                .addGap(7, 7, 7)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(tKK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(tTelepon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jLabel5))
                    .addComponent(rbAktif)
                    .addComponent(rbTidakAktif))
                .addGap(7, 7, 7)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnSimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(41, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
       validasi();
    }//GEN-LAST:event_formWindowOpened

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        // TODO add your handling code here:
        if (tKode.getText().isEmpty() || tNik.getText().isEmpty() || tNama.getText().isEmpty() 
                || tAlamat.getText().isEmpty() ||  rbLaki.isSelected() == false
                &&  rbPerempuan.isSelected() == false ||  tKK.getText().isEmpty()
                ||  tTelepon.getText().isEmpty() ||  rbAktif.isSelected() == false 
                && rbTidakAktif.isSelected() == false || tKet.getText().isEmpty()) {
            Messages.setErrorMessage("Lengkapi data terlebih dahulu..!");
        } else if (tNik.getText().length() != 16) {
            Messages.setErrorMessage("Nik wajib berisi 16 digit..!");
        } else if (tNama.getText().length() < 3 || tNama.getText().length() > 50) {
            Messages.setErrorMessage("Nama berisi 3-50 digit..!");
        } else if (tKK.getText().length() != 10) {
            Messages.setErrorMessage("No.KK wajib berisi 10 digit..!");
        } else if (tTelepon.getText().length() < 11 || tTelepon.getText().length() > 12) {
            Messages.setErrorMessage("Nomor Telepon berisi 11-12 digit..!");
        } else {
            String jenis, status;
            if (rbLaki.isSelected()) {
                jenis = "Laki-Laki";
            } else {
                jenis = "Perempuan";
            }
            if (rbAktif.isSelected()) {
                status = "AKTIF";
            } else {
                status = "TIDAK AKTIF";
            }
            try {
                Pelanggan k = new Pelanggan();
                k.setKode(tKode.getText());
                k.setNik(tNik.getText());
                k.setNama(tNama.getText());
                k.setJk(jenis);
                k.setAlamat(tAlamat.getText());
                k.setKk(tKK.getText());
                k.setTelepon(tTelepon.getText());
                k.setKeterangan(tKet.getText());
                k.setStatus(status);
                if ("INSERT".equals(aksi)) {
                    //Menambah record baru ke database
                    i.insert(k);
                    Messages.setInfomationMessage("Data telah berhasil disimpan");
                    bersih();
                } else {
                    //Mengubah record yang sudah ada di database
                    i.update(k);
                    Messages.setInfomationMessage("Data telah berhasil diperbaharui");
                    dispose();
                }
            } catch (SQLException ex) {
                Messages.setErrorMessage("Ada kesalahan dalam SQL statement..!" + ex.toString());
            }
        }
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void tNikKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tNikKeyTyped
        // TODO add your handling code here:
        if (!Character.isDigit(evt.getKeyChar())) {
            evt.consume();
        }
    }//GEN-LAST:event_tNikKeyTyped

    private void tNamaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tNamaKeyTyped
        // TODO add your handling code here:
        if (!Character.isLetter(evt.getKeyChar()) && !(evt.getKeyChar()== KeyEvent.VK_SPACE)) { //validasi space
            evt.consume();
        }
    }//GEN-LAST:event_tNamaKeyTyped

    private void tKKKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tKKKeyTyped
        // TODO add your handling code here:
        if (!Character.isDigit(evt.getKeyChar())) {
            evt.consume();
        }
    }//GEN-LAST:event_tKKKeyTyped

    private void tTeleponKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tTeleponKeyTyped
        // TODO add your handling code here:
        if (!Character.isDigit(evt.getKeyChar())) {
            evt.consume();
        }
    }//GEN-LAST:event_tTeleponKeyTyped

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
        switch(aksi) {
            case "VIEW":
                new FrmRiwayatPelanggan().show();
                this.dispose();
                break;
            default:
                this.dispose();
                break;
        }
    }//GEN-LAST:event_formWindowClosed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmMasterPelanggan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmMasterPelanggan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmMasterPelanggan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmMasterPelanggan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmMasterPelanggan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSimpan;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JRadioButton rbAktif;
    private javax.swing.JRadioButton rbLaki;
    private javax.swing.JRadioButton rbPerempuan;
    private javax.swing.JRadioButton rbTidakAktif;
    private javax.swing.JTextArea tAlamat;
    private javax.swing.JTextField tKK;
    private javax.swing.JTextArea tKet;
    private javax.swing.JTextField tKode;
    private javax.swing.JTextField tNama;
    private javax.swing.JTextField tNik;
    private javax.swing.JTextField tTelepon;
    // End of variables declaration//GEN-END:variables
}
