/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package id.sch.smkn1kawali.penjualanmotor.views.mains;

import id.sch.smkn1kawali.penjualanmotor.controllers.ControllerPembayaran;
import id.sch.smkn1kawali.penjualanmotor.interfaces.InterfacePembayaran;
import id.sch.smkn1kawali.penjualanmotor.models.Pembayaran;
import id.sch.smkn1kawali.penjualanmotor.models.tables.TableAngsuran;
import id.sch.smkn1kawali.penjualanmotor.models.tables.TableDaftarMotor;
import id.sch.smkn1kawali.penjualanmotor.utilitys.DateRenderer;
import id.sch.smkn1kawali.penjualanmotor.utilitys.Messages;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.SpinnerNumberModel;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Acer One
 */
public class FrmPembayaran extends javax.swing.JInternalFrame {
    InterfacePembayaran i;
    List<Pembayaran> l = new ArrayList<>();
    int id, sisa, max, angsuran, cicilan;
    
    /**
     * Creates new form FrmPembayaran
     */
    public FrmPembayaran() {
        initComponents();
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0,0,0,0));
        BasicInternalFrameUI ui = (BasicInternalFrameUI)this.getUI();
        ui.setNorthPane(null);
        i = new ControllerPembayaran();
    }
    
    //method untuk men/gosongkan jTextBox dan jComboBox pada Form
    private void BersihData() {
        id = 0;
        tKode.setText("");
        lKode.setText("-");
        lDiskon.setText("-");
        lPajak.setText("-");
        lTotal.setText("-");
        lAngsuran.setText("-");
        lTipe.setText("-");
        tBayar.setText("");
        lSisa.setText("Sisa Pembayaran : Rp.0");
        sisa = 0;
        tbl.setModel(new DefaultTableModel());
        tbl1.setModel(new DefaultTableModel());
    }
    
    private void SetEditOff() {
        jLabel7.setVisible(false);
        lAngsuran.setVisible(false);
        jLabel12.setVisible(false);
        jScrollPane2.setVisible(false);
        tbl1.setVisible(false);
        jLabel18.setVisible(false);
        jLabel14.setVisible(false);
        jSpinner1.setVisible(false);
        jLabel15.setVisible(false);
        lBayar.setVisible(false);
    }
    
    private void SetEditOn() {
        jLabel7.setVisible(true);
        lAngsuran.setVisible(true);
        jLabel12.setVisible(true);
        jScrollPane2.setVisible(true);
        tbl1.setVisible(true);
        jLabel14.setVisible(true);
        jSpinner1.setVisible(true);
        jLabel15.setVisible(true);
        lBayar.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tKode = new javax.swing.JTextField();
        btnCari = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lKode = new javax.swing.JLabel();
        lDiskon = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        lPajak = new javax.swing.JLabel();
        lTotal = new javax.swing.JLabel();
        lAngsuran = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl = new javax.swing.JTable();
        jLabel16 = new javax.swing.JLabel();
        lSisa = new javax.swing.JLabel();
        tBayar = new javax.swing.JTextField();
        btnBayar = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        lTipe = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl1 = new javax.swing.JTable();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        lStatus = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jSpinner1 = new javax.swing.JSpinner();
        jLabel15 = new javax.swing.JLabel();
        lBayar = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("PEMBAYARAN");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 10, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Masukan Kode Pembelian");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 72, -1, -1));

        tKode.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(tKode, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 95, 212, -1));

        btnCari.setBackground(new java.awt.Color(42, 39, 41));
        btnCari.setForeground(new java.awt.Color(255, 255, 255));
        btnCari.setText("Cari");
        btnCari.setBorder(null);
        btnCari.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCariActionPerformed(evt);
            }
        });
        getContentPane().add(btnCari, new org.netbeans.lib.awtextra.AbsoluteConstraints(245, 93, 70, 30));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Detail Pembelian");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 152, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Kode Pembelian");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 202, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Pajak");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 314, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Total Harga");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 370, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Angsuran");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 490, -1, -1));

        lKode.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lKode.setText("-");
        getContentPane().add(lKode, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 223, -1, -1));

        lDiskon.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lDiskon.setText("-");
        getContentPane().add(lDiskon, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 279, -1, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setText("Diskon");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 258, -1, -1));

        lPajak.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lPajak.setText("-");
        getContentPane().add(lPajak, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 335, -1, -1));

        lTotal.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lTotal.setText("-");
        getContentPane().add(lTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 392, -1, -1));

        lAngsuran.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lAngsuran.setText("-");
        getContentPane().add(lAngsuran, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 520, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("Daftar Motor");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 230, -1, -1));

        tbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tbl);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(337, 253, 489, 120));

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel16.setText("Rp.");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 470, -1, 30));

        lSisa.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lSisa.setText("Sisa Pembayaran: Rp.0");
        getContentPane().add(lSisa, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 500, -1, -1));

        tBayar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tBayar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tBayarKeyTyped(evt);
            }
        });
        getContentPane().add(tBayar, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 470, 212, -1));

        btnBayar.setBackground(new java.awt.Color(42, 39, 41));
        btnBayar.setForeground(new java.awt.Color(255, 255, 255));
        btnBayar.setText("Bayar");
        btnBayar.setBorder(null);
        btnBayar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBayar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBayarActionPerformed(evt);
            }
        });
        getContentPane().add(btnBayar, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 470, 70, 30));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setText("Tipe Pembayaran");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(337, 394, -1, -1));

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel18.setText("Untuk Melihat Daftar Angsuran Pilih Daftar Motor dahulu");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 370, 310, 30));

        lTipe.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lTipe.setText("-");
        getContentPane().add(lTipe, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 420, 100, -1));
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(1180, 160, -1, -1));

        tbl1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tbl1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbl1);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(337, 100, 489, 120));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel12.setText("Daftar Motor");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 80, -1, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel13.setText("Status");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 427, -1, -1));

        lStatus.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lStatus.setText("-");
        getContentPane().add(lStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 455, -1, -1));

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel17.setText("Masukan Jumlah Pembayaran");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 450, -1, -1));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel14.setText("Bayar");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 415, -1, 20));

        jSpinner1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpinner1StateChanged(evt);
            }
        });
        getContentPane().add(jSpinner1, new org.netbeans.lib.awtextra.AbsoluteConstraints(505, 415, -1, -1));

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel15.setText("Bulan");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 415, 30, 20));

        lBayar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lBayar.setText("Total Bayar : Rp. 0");
        getContentPane().add(lBayar, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 415, 240, 20));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
        // TODO add your handling code here:
        BersihData();
        SetEditOff();
        tbl.setEnabled(false);
        tBayar.setEnabled(false);
        btnBayar.setEnabled(false);
    }//GEN-LAST:event_formInternalFrameOpened

    private void btnCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCariActionPerformed
        // TODO add your handling code here:
        if (tKode.getText().equals("")) {
            Messages.setErrorMessage("Masukan kode kredit terlebih dahulu");
        } else if (tKode.getText().length() != 15) {
            Messages.setErrorMessage("Kode kredit berjumlah 15 digit");
        } else {
            try {
                Pembayaran p = i.getDataById(tKode.getText());
                if (tKode.getText().equals(p.getKode())) {
                    if (tKode.getText().equals(p.getKode())) {
                        if (p.getKeterangan().equals("LUNAS")) {
                            Messages.setErrorMessage("Kode Pembelian yang anda masukan sudah melunasi pembayaran");
                        } else {
                            id = p.getId();
                            lKode.setText(p.getKode());
                            lDiskon.setText(p.getDiskon() + "%");
                            lPajak.setText(p.getPajak() + "%");
                            lTotal.setText("Rp. " + p.getTotal());
                            lStatus.setText(p.getKeterangan());
                            lTipe.setText(p.getTipe());
                            lSisa.setText("Sisa pembayaran : Rp. " + p.getSisa());
                            sisa = p.getSisa();
                            if (lTipe.getText().equals("TUNAI")) {
                                SetEditOff();
                                jLabel8.setText("Daftar Motor");
                                l = i.getData(tKode.getText());
                                TableDaftarMotor t = new TableDaftarMotor(l);
                                tbl.setModel(t);
                                jLabel17.setText("Masukan Jumlah Pembayaran");
                                
                            } else {
                                Pembayaran s = i.getSale(tKode.getText());
                                if (s.getBayar() == 0) {
                                    SetEditOff();
                                    jLabel8.setText("Daftar Motor");
                                    l = i.getData(tKode.getText());
                                    TableDaftarMotor t = new TableDaftarMotor(l);
                                    tbl.setModel(t);
                                    jLabel17.setText("Masukan Uang Muka");
                                } else {
                                    SetEditOn();
                                    lAngsuran.setText("Rp. " + p.getAngsuran());
                                    angsuran = p.getAngsuran();
                                    jLabel8.setText("Daftar Angsuran");
                                    l = i.getData(tKode.getText());
                                    TableDaftarMotor t = new TableDaftarMotor(l);
                                    tbl1.setModel(t);
                                    jLabel17.setText("Masukan Angsuran");
                                    tbl.setModel(new DefaultTableModel());
                                    //====================================
                                    l = i.getAngsuran(tKode.getText());
                                    TableAngsuran u = new TableAngsuran(l);
                                    tbl.setModel(u);
                                    //====================================
                                    tbl.getColumnModel().getColumn(1).setCellRenderer(new DateRenderer());
                                    int row = tbl.getRowCount();
                                    if (row == 0) {
                                        max = p.getCicilan();
                                    } else {
                                        Pembayaran b = i.getSum(tKode.getText());
                                        int m = p.getCicilan();
                                        int n = b.getCicilan();
                                        max = m - n;
                                    }
                                    System.out.println(max);
                                    SpinnerNumberModel value = new SpinnerNumberModel(0, 0, max, 1);
                                    jSpinner1.setModel(value);
                                }
                            }
                            
                            tBayar.setEnabled(true);
                            btnBayar.setEnabled(true);
                        } 
                    } else {
                        Messages.setErrorMessage("Kode kredit yang anda masukan tidak ditemukan pada database");
                    }
                } else {
                    Messages.setErrorMessage("Kode Kredit tidak ditemukan pada database");
                }
                
            } catch (SQLException ex) {
                Messages.setErrorMessage("Ada kesalahan dalam SQL statement..!" + ex.toString());
            }
        }
    }//GEN-LAST:event_btnCariActionPerformed

    private void btnBayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBayarActionPerformed
        // TODO add your handling code here:
        if (tKode.getText().equals("") || tBayar.getText().equals("")) {
            Messages.setErrorMessage("Lengkapi data terlebih dahulu");
        } else if (tBayar.getText().length() < 7 || tBayar.getText().length() > 8) {
            Messages.setErrorMessage("Jumlah Pembayaran berkisar 7-8 digit saja");
        } else {
            try {
                Pembayaran p = new Pembayaran();
                Integer bayar = Integer.parseInt(tBayar.getText());
                Integer kembalian1 = bayar - sisa;
                Integer kembalian2 = bayar - cicilan;
                Integer sisa1 = sisa - cicilan;
                Integer hasil = sisa - bayar;
                if (lTipe.getText().equals("TUNAI")) {
                    if (sisa > bayar) {
                        Messages.setErrorMessage("Pembayaran tidak boleh kurang dari sisa pembayaran");
                    } else {
                        p.setId(id);
                        p.setBayar(bayar);
                        p.setKembalian(kembalian1);
                        p.setSisa(0);
                        i.updateDetail(p);
                        //============================== CHANGE STATUS
                        p.setKode(tKode.getText());
                        i.statusCash(p);
                        Messages.setInfomationMessage("Data telah berhasil disimpan \nKEMBALIAN anda Rp. " + kembalian1);
                        //==============================
                        Pembayaran x = i.getDetailById(id);
                        FrmDetailCash f = new FrmDetailCash();
                        f.getNama().setText(x.getNama());
                        f.getNik().setText(x.getNik());
                        f.getAlamat().setText(x.getAlamat());
                        f.getTipe().setText(x.getTipe());
                        f.getWarna().setText(x.getWarna());
                        f.getHarga().setText("Rp. " + String.format("%,.2f", Double.valueOf(x.getHarga())));
                        f.getKode().setText(x.getKode());
                        f.getDiskon().setText(x.getDiskon() + "%");
                        f.getPajak().setText(x.getPajak() + "%");
                        f.show();
                    }
                } else {
                    Pembayaran s = i.getSale(tKode.getText());
                    if (s.getBayar() == 0) {
                        if (bayar > sisa) {
                            Messages.setErrorMessage("Uang Muka tidak boleh lebih dari sisa pembayaran");
                        } else {
                            Double angsuran = Double.valueOf(hasil) / 12;
                            p.setId(id);
                            p.setBayar(bayar);
                            p.setKembalian(0);
                            p.setSisa(hasil);
                            i.updateDetail(p);
                            //============================== CHANGE STATUS
                            p.setKode(tKode.getText());
                            p.setAngsuran((int) Math.ceil(angsuran));
                            p.setKeterangan("BELUM LUNAS");
                            i.statusCredit(p);
                            //============================== INFO
                            Pembayaran x = i.getDetailById(id);
                            FrmDetailKredit f = new FrmDetailKredit();
                            f.getNama().setText(x.getNama());
                            f.getNik().setText(x.getNik());
                            f.getAlamat().setText(x.getAlamat());
                            f.getTipe().setText(x.getTipe());
                            f.getWarna().setText(x.getWarna());
                            f.getHarga().setText("Rp. " + String.format("%,.2f", Double.valueOf(x.getHarga())));
                            f.getKode().setText(x.getKode());
                            f.getUang().setText("Rp. " + String.format("%,.2f", Double.valueOf(x.getUang())));
                            f.getDiskon().setText(x.getDiskon() + "%");
                            f.getPajak().setText(x.getPajak() + "%");
                            f.getBunga().setText(x.getBunga() + "%");
                            f.getCicilan().setText(x.getCicilan() + " Bulan");
                            f.getAngsuran().setText("Rp. " + String.format("%,.2f", Double.valueOf(x.getAngsuran())));
                            f.show();
                            BersihData();
                            SetEditOff();
                        }
                    } else {
                        if (jSpinner1.getValue().equals(0)) {
                            Messages.setErrorMessage("Masukan bayar terlebih dahulu");
                        } else if (bayar < cicilan) {
                            Messages.setErrorMessage("Pembayaran tidak boleh kurang dari Total Bayar");
                        } else {
                            Pembayaran a = new Pembayaran();
                            a.setKode(tKode.getText());
                            a.setCicilan((Integer) jSpinner1.getValue());
                            a.setJumlah(cicilan);
                            a.setBayar(Integer.parseInt(tBayar.getText()));
                            a.setKembalian(kembalian2);
                            a.setSisa(sisa1);
                            if (jSpinner1.getValue().equals(max)) {
                                i.insertAngsuran(a);
                                i.status(a);
                                Messages.setInfomationMessage("Selamat Pembayaran Kredit Anda sudah Lunas");
                            } else {
                                i.insertAngsuran(a);
                                i.update(a);
                                Messages.setInfomationMessage("Data telah berhasil disimpan \nKEMBALIAN anda Rp. " + kembalian2);
                            }
                            
//                            Double angsuran = Double.valueOf(hasil) / 12;
//                            p.setId(id);
//                            p.setBayar(bayar);
//                            p.setKembalian(0);
//                            p.setSisa(hasil);
//                            i.updateDetail(p);
//                            //============================== CHANGE STATUS
//                            p.setKode(tKode.getText());
//                            p.setAngsuran((int) Math.ceil(angsuran));
//                            p.setKeterangan("BELUM LUNAS");
//                            i.statusCredit(p);
//                            //============================== INFO
//                            Pembayaran x = i.getDetailById(id);
//                            FrmDetailKredit f = new FrmDetailKredit();
//                            f.getNama().setText(s.getNama());
//                            f.getNik().setText(s.getNik());
//                            f.getAlamat().setText(s.getAlamat());
//                            f.getTipe().setText(s.getTipe());
//                            f.getWarna().setText(s.getWarna());
//                            f.getHarga().setText("Rp. " + String.format("%,.2f", Double.valueOf(s.getHarga())));
//                            f.getKode().setText(s.getKode());
//                            f.getUang().setText("Rp. " + String.format("%,.2f", Double.valueOf(s.getUang())));
//                            f.getDiskon().setText(s.getDiskon() + "%");
//                            f.getPajak().setText(s.getPajak() + "%");
//                            f.getBunga().setText(s.getBunga() + "%");
//                            f.getCicilan().setText(s.getCicilan() + " Bulan");
//                            f.getAngsuran().setText("Rp. " + String.format("%,.2f", Double.valueOf(s.getAngsuran())));
//                            f.show();
                            BersihData();
                            SetEditOff();
                        }
                    }
                }
                
                //int bayar = Integer.parseInt(v.getJSpinner().getValue().toString());
//                int jumlah = Integer.parseInt(v.getTxtJumlah().getText());
//                Pembayaran a = new Pembayaran();
//                a.setKdKredit(v.getTxtKdKredit().getText());
//                a.setTanggal(tanggal);
//                //a.setBayar(bayar);
//                a.setJumlah(jumlah);
//                
//                //Messages.setInfomationMessage("Data telah berhasil disimpan");
//                //=================================================================
//                Pembayaran b = new Pembayaran();
//                int z = y - jumlah;
//                b.setSisa(z);
//                b.setKdKredit(v.getTxtKdKredit().getText());
//                
//                if (jumlah == y) {
//                    i.insert(a);
//                    i.changeStatus(b);
//                    Messages.setInfomationMessage("Selamat pembayaran anda sudah LUNAS");
//                } else {
//                    i.insert(a);
//                    i.update(b);
//                    Messages.setInfomationMessage("Sisa pembayaran anda Rp. " + z);
//                }
//                //=================================================================
//                l = i.getData(v.getTxtKdKredit().getText());
//                TableDaftarMotor t = new TableDaftarMotor(l);
//                v.getTblAngsuran().setModel(t);
//                BersihData();
//                SetEditOff();
            } catch (SQLException ex) {
                Logger.getLogger(FrmPembayaran.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnBayarActionPerformed

    private void tBayarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tBayarKeyTyped
        // TODO add your handling code here:
        if (!Character.isDigit(evt.getKeyChar())) {
            evt.consume();
        }
    }//GEN-LAST:event_tBayarKeyTyped

    private void tbl1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl1MouseClicked
        try {
            // TODO add your handling code here:
            
        } catch (Exception ex) {
            Logger.getLogger(FrmPembayaran.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_tbl1MouseClicked

    private void jSpinner1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSpinner1StateChanged
        // TODO add your handling code here:
        if (jSpinner1.getValue().equals(max)) {
            cicilan = sisa;
            lBayar.setText("Total Bayar : Rp. " + String.format("%,.2f", Double.valueOf(cicilan)));
        } else {
            int value = (Integer)jSpinner1.getValue();
            cicilan = angsuran * value;
            lBayar.setText("Total Bayar : Rp. " + String.format("%,.2f", Double.valueOf(cicilan)));
        }
    }//GEN-LAST:event_jSpinner1StateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBayar;
    private javax.swing.JButton btnCari;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JLabel lAngsuran;
    private javax.swing.JLabel lBayar;
    private javax.swing.JLabel lDiskon;
    private javax.swing.JLabel lKode;
    private javax.swing.JLabel lPajak;
    private javax.swing.JLabel lSisa;
    private javax.swing.JLabel lStatus;
    private javax.swing.JLabel lTipe;
    private javax.swing.JLabel lTotal;
    private javax.swing.JTextField tBayar;
    private javax.swing.JTextField tKode;
    private javax.swing.JTable tbl;
    private javax.swing.JTable tbl1;
    // End of variables declaration//GEN-END:variables
}
