/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package id.sch.smkn1kawali.penjualanmotor.views;

import id.sch.smkn1kawali.penjualanmotor.controllers.ControllerUser;
import id.sch.smkn1kawali.penjualanmotor.interfaces.InterfaceUser;
import id.sch.smkn1kawali.penjualanmotor.models.User;
import id.sch.smkn1kawali.penjualanmotor.views.mains.FrmLapPenjualan;
import id.sch.smkn1kawali.penjualanmotor.views.mains.FrmLapPembelian;
import id.sch.smkn1kawali.penjualanmotor.views.mains.FrmPembayaran;
import id.sch.smkn1kawali.penjualanmotor.views.mains.FrmDataKaryawan;
import id.sch.smkn1kawali.penjualanmotor.utilitys.Messages;
import id.sch.smkn1kawali.penjualanmotor.views.mains.FrmDataMotor;
import id.sch.smkn1kawali.penjualanmotor.views.mains.FrmDataPelanggan;
import id.sch.smkn1kawali.penjualanmotor.views.mains.FrmPembelian;
import id.sch.smkn1kawali.penjualanmotor.views.mains.FrmDataUser;
import java.awt.Color;
import java.awt.Cursor;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDesktopPane;
import javax.swing.JLabel;

/**
 *
 * @author Acer One
 */
public class FrmMenuUtama extends javax.swing.JFrame {

    public static String id;
    public static String nama;
    public static String jenisUser;
    Color DefaultColor, ActiveColor;
    InterfaceUser i;
    
    /**
     * Creates new form FrmMenuUtama
     */
    public FrmMenuUtama() {
        initComponents();
        i = new ControllerUser();
    }
    
    //method buat tanggal
    public void buattanggal() {
        Date tgl = new Date();
        SimpleDateFormat sdf = new SimpleDateFormat("dd-MM-yyyy");
        lTanggal.setText(": " + sdf.format(tgl));
    }
    
    //method validasi
    public void validasi() {
        try {
            if (jenisUser.equalsIgnoreCase("Admin")) {
                jPanel4.setVisible(true);
                Menu1.setVisible(true);
                Menu2.setVisible(true);
                Menu3.setVisible(true);
                Menu4.setVisible(true);
                Menu5.setVisible(true);
                Menu6.setVisible(true);
                FrmDataKaryawan frmKaryawan = new FrmDataKaryawan();
                jDesktopPane1.removeAll();
                jDesktopPane1.add(frmKaryawan).setVisible(true);
            } else {
                jPanel5.setVisible(false);
                Menu1.setVisible(false);
                Menu2.setVisible(false);
                Menu3.setVisible(false);
                Menu4.setVisible(false);
                bar(SidePanel5);
                FrmPembelian frmPembelian = new FrmPembelian();
                jDesktopPane1.removeAll();
                jDesktopPane1.add(frmPembelian).setVisible(true);
            }
        } catch (Exception e) {
            Messages.setErrorMessage("Ada Kesalahan pada Kode Program");
        }
    }
    
    //method side panel
    public void bar(JLabel lab){
        SidePanel1.setOpaque(false);
        SidePanel2.setOpaque(false);
        SidePanel3.setOpaque(false);
        SidePanel4.setOpaque(false);
        SidePanel5.setOpaque(false);
        SidePanel6.setOpaque(false);
        SidePanel7.setOpaque(false);
        SidePanel8.setOpaque(false);
        lab.setOpaque(true);
        jPanel3.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lNama = new javax.swing.JLabel();
        lTanggal = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        Menu1 = new javax.swing.JPanel();
        SidePanel1 = new javax.swing.JLabel();
        MenuItem1 = new javax.swing.JLabel();
        Menu2 = new javax.swing.JPanel();
        MenuItem2 = new javax.swing.JLabel();
        SidePanel2 = new javax.swing.JLabel();
        Menu3 = new javax.swing.JPanel();
        MenuItem3 = new javax.swing.JLabel();
        SidePanel3 = new javax.swing.JLabel();
        Menu4 = new javax.swing.JPanel();
        MenuItem4 = new javax.swing.JLabel();
        SidePanel4 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        Menu5 = new javax.swing.JPanel();
        SidePanel5 = new javax.swing.JLabel();
        MenuItem5 = new javax.swing.JLabel();
        Menu6 = new javax.swing.JPanel();
        MenuItem6 = new javax.swing.JLabel();
        SidePanel6 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        Menu7 = new javax.swing.JPanel();
        MenuItem7 = new javax.swing.JLabel();
        SidePanel7 = new javax.swing.JLabel();
        Menu8 = new javax.swing.JPanel();
        MenuItem8 = new javax.swing.JLabel();
        SidePanel8 = new javax.swing.JLabel();
        jDesktopPane1 = new javax.swing.JDesktopPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(192, 27, 54));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Tanggal");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(919, 13, -1, -1));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("User Login");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(919, 36, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/id/sch/smkn1kawali/penjualanmotor/images/shutdown-icon-18-ffffff-20.png"))); // NOI18N
        jLabel3.setToolTipText("Logout");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel3MouseEntered(evt);
            }
        });
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 60, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/id/sch/smkn1kawali/penjualanmotor/images/close-window-icon-ffffff-20.png"))); // NOI18N
        jLabel4.setToolTipText("Exit");
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel4MouseEntered(evt);
            }
        });
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 60, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/id/sch/smkn1kawali/penjualanmotor/images/logo-60.png"))); // NOI18N
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, 70));

        lNama.setForeground(new java.awt.Color(255, 255, 255));
        lNama.setText(": -");
        jPanel2.add(lNama, new org.netbeans.lib.awtextra.AbsoluteConstraints(982, 36, -1, -1));

        lTanggal.setForeground(new java.awt.Color(255, 255, 255));
        lTanggal.setText(": -");
        jPanel2.add(lTanggal, new org.netbeans.lib.awtextra.AbsoluteConstraints(982, 13, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("MANAGEMENT SYSTEM");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, -1, 30));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("PT. PUTRA PRATAMA MOTOR");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 40, -1, 30));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/id/sch/smkn1kawali/penjualanmotor/images/help-20.png"))); // NOI18N
        jLabel10.setToolTipText("Help");
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel10MouseEntered(evt);
            }
        });
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 60, -1, -1));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/id/sch/smkn1kawali/penjualanmotor/images/code-20.png"))); // NOI18N
        jLabel11.setToolTipText("Info Programmer");
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel11MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel11MouseEntered(evt);
            }
        });
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 60, -1, -1));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/id/sch/smkn1kawali/penjualanmotor/images/info-20.png"))); // NOI18N
        jLabel12.setToolTipText("Info Program");
        jLabel12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel12MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel12MouseEntered(evt);
            }
        });
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 60, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1100, 90));

        jPanel3.setBackground(new java.awt.Color(42, 39, 41));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel13.setText(" Data");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 125, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        Menu1.setBackground(new java.awt.Color(42, 39, 41));
        Menu1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Menu1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        SidePanel1.setBackground(new java.awt.Color(192, 27, 54));
        SidePanel1.setOpaque(true);
        Menu1.add(SidePanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 10, 50));

        MenuItem1.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        MenuItem1.setForeground(new java.awt.Color(204, 204, 204));
        MenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/id/sch/smkn1kawali/penjualanmotor/images/administrator-32.png"))); // NOI18N
        MenuItem1.setText(" Data Karyawan");
        MenuItem1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MenuItem1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                MenuItem1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                MenuItem1MouseExited(evt);
            }
        });
        Menu1.add(MenuItem1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 170, 50));

        Menu2.setBackground(new java.awt.Color(42, 39, 41));
        Menu2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Menu2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        MenuItem2.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        MenuItem2.setForeground(new java.awt.Color(204, 204, 204));
        MenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/id/sch/smkn1kawali/penjualanmotor/images/contacts-32.png"))); // NOI18N
        MenuItem2.setText(" Data User");
        MenuItem2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MenuItem2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                MenuItem2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                MenuItem2MouseExited(evt);
            }
        });
        Menu2.add(MenuItem2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 170, 50));

        SidePanel2.setBackground(new java.awt.Color(192, 27, 54));
        Menu2.add(SidePanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 10, 50));

        Menu3.setBackground(new java.awt.Color(42, 39, 41));
        Menu3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Menu3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        MenuItem3.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        MenuItem3.setForeground(new java.awt.Color(204, 204, 204));
        MenuItem3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/id/sch/smkn1kawali/penjualanmotor/images/motorcycle-32.png"))); // NOI18N
        MenuItem3.setText(" Data Motor");
        MenuItem3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MenuItem3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                MenuItem3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                MenuItem3MouseExited(evt);
            }
        });
        Menu3.add(MenuItem3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 170, 50));

        SidePanel3.setBackground(new java.awt.Color(192, 27, 54));
        Menu3.add(SidePanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 10, 50));

        Menu4.setBackground(new java.awt.Color(42, 39, 41));
        Menu4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Menu4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        MenuItem4.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        MenuItem4.setForeground(new java.awt.Color(204, 204, 204));
        MenuItem4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/id/sch/smkn1kawali/penjualanmotor/images/conference-32.png"))); // NOI18N
        MenuItem4.setText(" Data Pelanggan");
        MenuItem4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MenuItem4MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                MenuItem4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                MenuItem4MouseExited(evt);
            }
        });
        Menu4.add(MenuItem4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 170, 50));

        SidePanel4.setBackground(new java.awt.Color(192, 27, 54));
        Menu4.add(SidePanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 10, 50));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel8.setText(" Transaksi");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 125, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        Menu5.setBackground(new java.awt.Color(42, 39, 41));
        Menu5.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Menu5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        SidePanel5.setBackground(new java.awt.Color(192, 27, 54));
        Menu5.add(SidePanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 10, 50));

        MenuItem5.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        MenuItem5.setForeground(new java.awt.Color(204, 204, 204));
        MenuItem5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/id/sch/smkn1kawali/penjualanmotor/images/banknotes-32.png"))); // NOI18N
        MenuItem5.setText(" Pembelian");
        MenuItem5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MenuItem5MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                MenuItem5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                MenuItem5MouseExited(evt);
            }
        });
        Menu5.add(MenuItem5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 170, 50));

        Menu6.setBackground(new java.awt.Color(42, 39, 41));
        Menu6.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Menu6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        MenuItem6.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        MenuItem6.setForeground(new java.awt.Color(204, 204, 204));
        MenuItem6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/id/sch/smkn1kawali/penjualanmotor/images/card-in-use-32.png"))); // NOI18N
        MenuItem6.setText(" Pembayaran");
        MenuItem6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MenuItem6MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                MenuItem6MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                MenuItem6MouseExited(evt);
            }
        });
        Menu6.add(MenuItem6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 170, 50));

        SidePanel6.setBackground(new java.awt.Color(192, 27, 54));
        Menu6.add(SidePanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 10, 50));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel9.setText(" Laporan");

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 125, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        Menu7.setBackground(new java.awt.Color(42, 39, 41));
        Menu7.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Menu7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        MenuItem7.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        MenuItem7.setForeground(new java.awt.Color(204, 204, 204));
        MenuItem7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/id/sch/smkn1kawali/penjualanmotor/images/report-2-32.png"))); // NOI18N
        MenuItem7.setText(" Penjualan");
        MenuItem7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MenuItem7MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                MenuItem7MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                MenuItem7MouseExited(evt);
            }
        });
        Menu7.add(MenuItem7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 170, 50));

        SidePanel7.setBackground(new java.awt.Color(192, 27, 54));
        Menu7.add(SidePanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 10, 50));

        Menu8.setBackground(new java.awt.Color(42, 39, 41));
        Menu8.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Menu8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        MenuItem8.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        MenuItem8.setForeground(new java.awt.Color(204, 204, 204));
        MenuItem8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/id/sch/smkn1kawali/penjualanmotor/images/report-3-32.png"))); // NOI18N
        MenuItem8.setText(" Pembelian");
        MenuItem8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MenuItem8MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                MenuItem8MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                MenuItem8MouseExited(evt);
            }
        });
        Menu8.add(MenuItem8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 170, 50));

        SidePanel8.setBackground(new java.awt.Color(192, 27, 54));
        Menu8.add(SidePanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 10, 50));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(Menu1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(Menu2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(Menu3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(Menu4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(Menu5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(Menu6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(Menu7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(Menu8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(Menu1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(Menu2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(Menu3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(Menu4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(Menu5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(Menu6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(Menu7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(Menu8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 190, 570));

        jDesktopPane1.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 910, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 570, Short.MAX_VALUE)
        );

        jPanel1.add(jDesktopPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 90, 910, 570));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        buattanggal();
        validasi();
        lNama.setText(": " + nama);
    }//GEN-LAST:event_formWindowOpened

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
        if (Messages.setConfirmMessage("Apakah anda yakin akan Logout?")) {
            this.dispose();
            new FrmLogin().show();
        }
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        // TODO add your handling code here:
        if (Messages.setConfirmMessage("Apakah Anda Yakin ingin keluar dari Aplikasi Ini ?")) {
            System.exit(0);
        }
    }//GEN-LAST:event_jLabel4MouseClicked

    private void MenuItem1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuItem1MouseClicked
        // TODO add your handling code here:
        bar(SidePanel1);
        FrmDataKaryawan frmKaryawan = new FrmDataKaryawan();
        jDesktopPane1.removeAll();
        jDesktopPane1.add(frmKaryawan).setVisible(true);
    }//GEN-LAST:event_MenuItem1MouseClicked

    private void MenuItem2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuItem2MouseClicked
        // TODO add your handling code here:
        bar(SidePanel2);
        FrmDataUser frmUser = new FrmDataUser();
        jDesktopPane1.removeAll();
        jDesktopPane1.add(frmUser).setVisible(true);
    }//GEN-LAST:event_MenuItem2MouseClicked

    private void MenuItem3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuItem3MouseClicked
        // TODO add your handling code here:
        bar(SidePanel3);
        FrmDataMotor frmMotor = new FrmDataMotor();
        jDesktopPane1.removeAll();
        jDesktopPane1.add(frmMotor).setVisible(true);
    }//GEN-LAST:event_MenuItem3MouseClicked

    private void MenuItem4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuItem4MouseClicked
        // TODO add your handling code here:
        bar(SidePanel4);
        FrmDataPelanggan frmPelanggan = new FrmDataPelanggan();
        jDesktopPane1.removeAll();
        jDesktopPane1.add(frmPelanggan).setVisible(true);
    }//GEN-LAST:event_MenuItem4MouseClicked

    private void MenuItem5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuItem5MouseClicked
        // TODO add your handling code here:
        bar(SidePanel5);
        FrmPembelian frmPembelian = new FrmPembelian();
        jDesktopPane1.removeAll();
        jDesktopPane1.add(frmPembelian).setVisible(true);
    }//GEN-LAST:event_MenuItem5MouseClicked

    private void MenuItem7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuItem7MouseClicked
        // TODO add your handling code here:
        bar(SidePanel7);
        FrmLapPenjualan frmLapBeliCash = new FrmLapPenjualan();
        jDesktopPane1.removeAll();
        jDesktopPane1.add(frmLapBeliCash).setVisible(true);
    }//GEN-LAST:event_MenuItem7MouseClicked

    private void MenuItem8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuItem8MouseClicked
        // TODO add your handling code here:
        bar(SidePanel8);
        FrmLapPembelian frmLapBeliKredit = new FrmLapPembelian();
        jDesktopPane1.removeAll();
        jDesktopPane1.add(frmLapBeliKredit).setVisible(true);
    }//GEN-LAST:event_MenuItem8MouseClicked

    private void MenuItem1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuItem1MouseEntered
        // TODO add your handling code here:
        Menu1.setBackground(Color.decode("#565255"));
        MenuItem1.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_MenuItem1MouseEntered

    private void MenuItem1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuItem1MouseExited
        // TODO add your handling code here:
        Menu1.setBackground(Color.decode("#2a2729"));
    }//GEN-LAST:event_MenuItem1MouseExited

    private void MenuItem2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuItem2MouseEntered
        // TODO add your handling code here:
        Menu2.setBackground(Color.decode("#565255"));
        MenuItem2.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_MenuItem2MouseEntered

    private void MenuItem2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuItem2MouseExited
        // TODO add your handling code here:
        Menu2.setBackground(Color.decode("#2a2729"));
    }//GEN-LAST:event_MenuItem2MouseExited

    private void MenuItem3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuItem3MouseEntered
        // TODO add your handling code here:
        Menu3.setBackground(Color.decode("#565255"));
        MenuItem3.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_MenuItem3MouseEntered

    private void MenuItem3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuItem3MouseExited
        // TODO add your handling code here:
        Menu3.setBackground(Color.decode("#2a2729"));
    }//GEN-LAST:event_MenuItem3MouseExited

    private void MenuItem4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuItem4MouseEntered
        // TODO add your handling code here:
        Menu4.setBackground(Color.decode("#565255"));
        MenuItem4.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_MenuItem4MouseEntered

    private void MenuItem4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuItem4MouseExited
        // TODO add your handling code here:
        Menu4.setBackground(Color.decode("#2a2729"));
    }//GEN-LAST:event_MenuItem4MouseExited

    private void MenuItem5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuItem5MouseEntered
        // TODO add your handling code here:
        Menu5.setBackground(Color.decode("#565255"));
        MenuItem5.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_MenuItem5MouseEntered

    private void MenuItem5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuItem5MouseExited
        // TODO add your handling code here:
        Menu5.setBackground(Color.decode("#2a2729"));
    }//GEN-LAST:event_MenuItem5MouseExited

    private void MenuItem7MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuItem7MouseEntered
        // TODO add your handling code here:
        Menu7.setBackground(Color.decode("#565255"));
        MenuItem7.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_MenuItem7MouseEntered

    private void MenuItem7MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuItem7MouseExited
        // TODO add your handling code here:
        Menu7.setBackground(Color.decode("#2a2729"));
    }//GEN-LAST:event_MenuItem7MouseExited

    private void MenuItem8MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuItem8MouseEntered
        // TODO add your handling code here:
        Menu8.setBackground(Color.decode("#565255"));
        MenuItem8.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_MenuItem8MouseEntered

    private void MenuItem8MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuItem8MouseExited
        // TODO add your handling code here:
        Menu8.setBackground(Color.decode("#2a2729"));
    }//GEN-LAST:event_MenuItem8MouseExited

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
        // TODO add your handling code here:
        new FrmBantuan().show();
    }//GEN-LAST:event_jLabel10MouseClicked

    private void jLabel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseClicked
        // TODO add your handling code here:
        new FrmInfoProgrammer().show();
    }//GEN-LAST:event_jLabel11MouseClicked

    private void jLabel12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseClicked
        // TODO add your handling code here:
        new FrmInfoProgram().show();
    }//GEN-LAST:event_jLabel12MouseClicked

    private void jLabel10MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseEntered
        // TODO add your handling code here:
        jLabel10.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_jLabel10MouseEntered

    private void jLabel12MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseEntered
        // TODO add your handling code here:
        jLabel12.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_jLabel12MouseEntered

    private void jLabel11MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseEntered
        // TODO add your handling code here:
        jLabel11.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_jLabel11MouseEntered

    private void jLabel3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseEntered
        // TODO add your handling code here:
        jLabel3.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_jLabel3MouseEntered

    private void jLabel4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseEntered
        // TODO add your handling code here:
        jLabel4.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_jLabel4MouseEntered

    private void MenuItem6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuItem6MouseClicked
        // TODO add your handling code here:
        bar(SidePanel6);
        FrmPembayaran frmAngsuran = new FrmPembayaran();
        jDesktopPane1.removeAll();
        jDesktopPane1.add(frmAngsuran).setVisible(true);
    }//GEN-LAST:event_MenuItem6MouseClicked

    private void MenuItem6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuItem6MouseEntered
        // TODO add your handling code here:
        Menu6.setBackground(Color.decode("#565255"));
        MenuItem6.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_MenuItem6MouseEntered

    private void MenuItem6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuItem6MouseExited
        // TODO add your handling code here:
        Menu6.setBackground(Color.decode("#2a2729"));
    }//GEN-LAST:event_MenuItem6MouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmMenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmMenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmMenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmMenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmMenuUtama().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Menu1;
    private javax.swing.JPanel Menu2;
    private javax.swing.JPanel Menu3;
    private javax.swing.JPanel Menu4;
    private javax.swing.JPanel Menu5;
    private javax.swing.JPanel Menu6;
    private javax.swing.JPanel Menu7;
    private javax.swing.JPanel Menu8;
    private javax.swing.JLabel MenuItem1;
    private javax.swing.JLabel MenuItem2;
    private javax.swing.JLabel MenuItem3;
    private javax.swing.JLabel MenuItem4;
    private javax.swing.JLabel MenuItem5;
    private javax.swing.JLabel MenuItem6;
    private javax.swing.JLabel MenuItem7;
    private javax.swing.JLabel MenuItem8;
    private javax.swing.JLabel SidePanel1;
    private javax.swing.JLabel SidePanel2;
    private javax.swing.JLabel SidePanel3;
    private javax.swing.JLabel SidePanel4;
    private javax.swing.JLabel SidePanel5;
    private javax.swing.JLabel SidePanel6;
    private javax.swing.JLabel SidePanel7;
    private javax.swing.JLabel SidePanel8;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JLabel lNama;
    private javax.swing.JLabel lTanggal;
    // End of variables declaration//GEN-END:variables
}
